try/finally only works in stages :(

diff --git a/Jenkinsfile-scripts-test b/Jenkinsfile-scripts-test
--- a/Jenkinsfile-scripts-test
+++ b/Jenkinsfile-scripts-test
@@ -45,71 +45,68 @@ pipeline {
         stash name: 'ccm', includes: '.stash-*'
       }
     }
-    try {
-      stage('Test Install Script (Linux)') {
-        agent { label 'mesos' }
-        steps {
-          checkout scm
-          unstash 'ccm'
-          sh '''#!/usr/bin/env bash
-             set -o errexit -o nounset -o pipefail
-             DCOS_URL="$(cat .stash-dcos-url)"
-             EXE_PATH="$(bin/install/install-binary-dcos-cli.sh "${DCOS_URL}")"
-             echo "${EXE_PATH}"
-             [[ -z "${EXE_PATH}" ]] && echo >&2 "Executable path not printed by install script. Failing build..." && exit 1
-             [[ ! -e "${EXE_PATH}" ]] && echo >&2 "Executable not found. Failing build..." && exit 1
-             '''
-        }
+    stage('Test Install Script (Linux)') {
+      agent { label 'mesos' }
+      steps {
+        checkout scm
+        unstash 'ccm'
+        sh '''#!/usr/bin/env bash
+           set -o errexit -o nounset -o pipefail
+           DCOS_URL="$(cat .stash-dcos-url)"
+           EXE_PATH="$(bin/install/install-binary-dcos-cli.sh "${DCOS_URL}")"
+           echo "${EXE_PATH}"
+           [[ -z "${EXE_PATH}" ]] && echo >&2 "Executable path not printed by install script. Failing build..." && exit 1
+           [[ ! -e "${EXE_PATH}" ]] && echo >&2 "Executable not found. Failing build..." && exit 1
+           '''
       }
-      stage('Test Install Script (Mac)') {
-        agent { label 'mac' }
-        steps {
-          checkout scm
-          unstash 'ccm'
-          sh '''#!/usr/bin/env bash
-             set -o errexit -o nounset -o pipefail
-             DCOS_URL="$(cat .stash-dcos-url)"
-             EXE_PATH="$(bin/install/install-binary-dcos-cli.sh "${DCOS_URL}")"
-             echo "${EXE_PATH}"
-             [[ -z "${EXE_PATH}" ]] && echo >&2 "Executable path not printed by install script. Failing build..." && exit 1
-             [[ ! -e "${EXE_PATH}" ]] && echo >&2 "Executable not found. Failing build..." && exit 1
-             '''
-        }
+    }
+    stage('Test Install Script (Mac)') {
+      agent { label 'mac' }
+      steps {
+        checkout scm
+        unstash 'ccm'
+        sh '''#!/usr/bin/env bash
+           set -o errexit -o nounset -o pipefail
+           DCOS_URL="$(cat .stash-dcos-url)"
+           EXE_PATH="$(bin/install/install-binary-dcos-cli.sh "${DCOS_URL}")"
+           echo "${EXE_PATH}"
+           [[ -z "${EXE_PATH}" ]] && echo >&2 "Executable path not printed by install script. Failing build..." && exit 1
+           [[ ! -e "${EXE_PATH}" ]] && echo >&2 "Executable not found. Failing build..." && exit 1
+           '''
       }
-      stage('Test Install Script (Windows)') {
-        agent { label 'windows' }
-        steps {
-          checkout scm
-          unstash 'ccm'
-          sh '''#!/usr/bin/env bash
-             set -o errexit -o nounset -o pipefail
-             DCOS_URL="$(cat .stash-dcos-url)"
-             EXE_PATH="$(bin/install/install-binary-dcos-cli.sh "${DCOS_URL}")"
-             echo "${EXE_PATH}"
-             [[ -z "${EXE_PATH}" ]] && echo >&2 "Executable path not printed by install script. Failing build..." && exit 1
-             [[ ! -e "${EXE_PATH}" ]] && echo >&2 "Executable not found. Failing build..." && exit 1
-             '''
-        }
+    }
+    stage('Test Install Script (Windows)') {
+      agent { label 'windows' }
+      steps {
+        checkout scm
+        unstash 'ccm'
+        sh '''#!/usr/bin/env bash
+           set -o errexit -o nounset -o pipefail
+           DCOS_URL="$(cat .stash-dcos-url)"
+           EXE_PATH="$(bin/install/install-binary-dcos-cli.sh "${DCOS_URL}")"
+           echo "${EXE_PATH}"
+           [[ -z "${EXE_PATH}" ]] && echo >&2 "Executable path not printed by install script. Failing build..." && exit 1
+           [[ ! -e "${EXE_PATH}" ]] && echo >&2 "Executable not found. Failing build..." && exit 1
+           '''
       }
-    } finally {
-      stage('Destroy CCM Cluster') {
-        agent { label 'mesos' }
-        when { expression { return params.DEBUG_BUILD } }
-        steps {
-          checkout scm
-          unstash 'ccm'
-          sh 'docker build -f cli/binary/Dockerfile.linux-binary -t linux-binary:${env.BUILD_NUMBER} .'
-          sh '''#!/usr/bin/env bash
-             set -o errexit -o nounset -o pipefail
-             CLUSTER_ID="$(cat .stash-cluster-id)"
-             docker run \
-                 --rm=true \
-                 --env CLUSTER_ID=${CLUSTER_ID} \
-                 --env CCM_AUTH_TOKEN=${param.CCM_AUTH_TOKEN} \
-                 linux-binary:${env.BUILD_NUMBER} \
-                 /bin/bash -c ../ccm/delete_ccm_cluster.sh
-             '''
-        }
+    }
+    stage('Destroy CCM Cluster') {
+      agent { label 'mesos' }
+      when { expression { return params.DEBUG_BUILD } }
+      steps {
+        checkout scm
+        unstash 'ccm'
+        sh 'docker build -f cli/binary/Dockerfile.linux-binary -t linux-binary:${env.BUILD_NUMBER} .'
+        sh '''#!/usr/bin/env bash
+           set -o errexit -o nounset -o pipefail
+           CLUSTER_ID="$(cat .stash-cluster-id)"
+           docker run \
+               --rm=true \
+               --env CLUSTER_ID=${CLUSTER_ID} \
+               --env CCM_AUTH_TOKEN=${param.CCM_AUTH_TOKEN} \
+               linux-binary:${env.BUILD_NUMBER} \
+               /bin/bash -c ../ccm/delete_ccm_cluster.sh
+           '''
       }
     }
   }
